services:
    app:
      build:
        context: .
        dockerfile: Dockerfile
      command: "fastapi dev src/main.py --host 0.0.0.0 --port 4000"
      volumes:
        - ./src:/app/src
      ports:
        - "4000:4000"