services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: "fastapi dev src/main.py --host 0.0.0.0 --port 4000"
    volumes:
      - ./src:/app/src
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d my_db -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5431:5432
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg:
